// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBlAToDkjAsiCNn2HuAVPlfN_KOtz04DM',
    appId: '1:912223951748:web:6115cfd1a3d9bdbbf59bd1',
    messagingSenderId: '912223951748',
    projectId: 'agente-de-transito',
    authDomain: 'agente-de-transito.firebaseapp.com',
    storageBucket: 'agente-de-transito.appspot.com',
    measurementId: 'G-LHJRGV52MS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0BsVHBwp5-SbyBCGNmuaYogSCokkdqKY',
    appId: '1:912223951748:android:927ec58778ee9552f59bd1',
    messagingSenderId: '912223951748',
    projectId: 'agente-de-transito',
    storageBucket: 'agente-de-transito.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCneln4iBCZwp1uJ5r-uFxoJLd8AJf400g',
    appId: '1:912223951748:ios:1e1f63748970711cf59bd1',
    messagingSenderId: '912223951748',
    projectId: 'agente-de-transito',
    storageBucket: 'agente-de-transito.appspot.com',
    iosBundleId: 'com.parcialf.agenteDeTransito',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCneln4iBCZwp1uJ5r-uFxoJLd8AJf400g',
    appId: '1:912223951748:ios:af9b42cabf9b8ecdf59bd1',
    messagingSenderId: '912223951748',
    projectId: 'agente-de-transito',
    storageBucket: 'agente-de-transito.appspot.com',
    iosBundleId: 'com.parcialf.agenteDeTransito.RunnerTests',
  );
}
